FROM golang:1.21 as builder
WORKDIR /app
COPY . .
RUN go mod tidy && go build -o server .

FROM gcr.io/distroless/base
COPY --from=builder /app/server /
EXPOSE 50051
ENTRYPOINT ["/server"]


...
docker build -t gcr.io/YOUR_PROJECT_ID/grpc-server .
docker push gcr.io/YOUR_PROJECT_ID/grpc-server


...
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: gcr.io/YOUR_PROJECT_ID/grpc-server
        ports:
        - containerPort: 50051



....
apiVersion: v1
kind: Service
metadata:
  name: grpc-service
spec:
  selector:
    app: grpc-server
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  type: ClusterIP



....
kubectl apply -f deployment.yaml
kubectl apply -f service.yaml


..

kubectl run grpc-client --image=appropriate/curl -i --tty --rm


...
grpcurl grpc-service:50051 list